---
# Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "shopping"
  labels:
    app: "shopping"
spec:
  to:
    kind: Service
    name: "shopping"
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: "shopping"
  labels:
    app: "shopping"
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: "shopping"
---
# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shopping
  labels:
    app: "shopping"
spec:
  replicas: 1
  strategy:
    #rollingUpdate:
    #  maxSurge: 1
    #  maxUnavailable: 0
    #type: RollingUpdate
  template:
    metadata:
      labels:
        app: "shopping"
    spec:
      serviceAccountName: default
      containers:
      - name: "shopping"
        image: "fabiogomezdiaz/session-mgmt-k8s-service-account:latest"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace