---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-matrix
  labels:    
    app: "shopping-matrix"
data:
  application.properties: |-
    sessions.maxSessions=20
---
# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shopping-matrix
  labels:    
    app: "shopping-matrix"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "shopping-matrix"
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: shopping-matrix
        items:
        - key: application.properties
          path: application.properties
      containers:
      - name: "shopping-matrix"
        image: "fabiogomezdiaz/shopping-matrix:latest"
        imagePullPolicy: "Always"
        env:
        - name: SPRING_CONFIG_LOCATION
          value: "/etc/config/application.properties"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3